// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otggeqoudcolxqqbtoth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90Z2dlcW91ZGNvbHhxcWJ0b3RoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjAzNTksImV4cCI6MjA2ODgzNjM1OX0.ZuFgD9lhf7uQzZS8bxeex5xASKkEAG_h9pTGoHEA6dQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});